### ISSUE TITLE
Duda ejercicio máquina expendedora. Comprobación contraseña

### ISSUE THREAD

**Issue by minicatsCB** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#24]
> **Paso 3**. Creamos varios métodos para gestionar a los clientes y sus necesidades
> - Metodos:
>     - Consultar saldo de un cliente
>         - Devolverá el saldo existente o *-1* en caso de error
>         - Comprobaremos la contraseña y el usuario
>     - Consultar gastos de un cliente
>         - Devolverá un array o *false* en caso de error
>         - Comprobaremos la contraseña y el usuario
> 
> [...]
> 
> - Protegeremos las funciones de gestión de usuarios con la contraseña *ficticiaMola*

En ambos consultas, a qué se refiere exactamente: ¿hay que comprobar la contraseña y usuario del cliente del cual estamos consultando el saldo, la contraseña y usuario del admin, o la contraseña *fictiziaMola*?

**Comment by UlisesGascon** [comment]
En principio la idea es que `admin` pueda añadir/quitar usuarios pero que cada usuario pueda consultar su propio saldo (user/pass validation) ;-)

**Comment by minicatsCB** [comment]
Entendido, gracias!
