### ISSUE TITLE
How to Sanitize Data with ES6 Template Strings

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#28]
https://wesbos.com/sanitize-html-es6-template-strings/

**Comment by calope03** [comment]
La libreria que viene en el enlace no funciona, esta es la ultima version: https://cdnjs.cloudflare.com/ajax/libs/dompurify/1.0.8/purify.min.js
Y cuando hace una llamada a `DomPurify` es `DOMPurify`

Tambien hace algo raro en el reduce que si lo arreglo os digo 😄

**Comment by UlisesGascon** [comment]
Igual esto ayuda...
- https://gomakethings.com/a-safer-alternative-to-innerhtml-with-vanilla-js/
- https://github.com/cferdinandi/saferInnerHTML/blob/master/src/js/saferInnerHTML.js
