### ISSUE TITLE
Necesito nombre para mi proyecto

### ISSUE THREAD

**Issue by calope03** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#32]
El caso es que lo tengo todo mas o menos montado, pero sigo sin saber que nombre ponerle, así que necesito recomendaciones.

El proyecto no tiene mas que el top 50 canciones del país en el que se encuentra el usuario y luego las fichas de cada artista con su correspondiente top 50.

![captura de pantalla 2018-11-26 a las 17 09 20](https://user-images.githubusercontent.com/29929180/49026582-81d2c200-f19e-11e8-9cf3-2ffbd690db3f.png)

![captura de pantalla 2018-11-26 a las 17 08 38](https://user-images.githubusercontent.com/29929180/49026572-7bdce100-f19e-11e8-91d2-5b3928f451e9.png)

Tiene mas o menos esta pinta.

**Comment by UlisesGascon** [comment]
GEO 50 Hits? :-P
