### ISSUE TITLE
Reto: Hack The Box

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#37]
### ¡Únete a Hack The Box](https://www.hackthebox.eu/invite) !

![screen-shot-2017-11-22-at-2 22 39-pm](https://user-images.githubusercontent.com/5110813/48711759-52efa580-ec0c-11e8-80e6-468101b8e14b.png)

¿Lo has logrado?

**:warning: No compartas como lo lograste**
> La primera regla de Hack The Box: Nadie habla sobre cómo registrarse en Hack The Box.

**Comment by alberto-gomez-munity** [comment]
![captura de pantalla 2018-12-25 a las 22 47 32](https://user-images.githubusercontent.com/7566625/50683298-e1c84e00-1011-11e9-9535-2ff24185adc8.png)

**Comment by UlisesGascon** [comment]
bravo @alberto-gomez-munity !

**Comment by codemcu** [comment]
Otro más por aquí :smiley:

![hackthebox](https://user-images.githubusercontent.com/6061416/50798648-64366380-12d9-11e9-8eaf-6813ef0089a8.png)

**Comment by UlisesGascon** [comment]
genial @codemcu !!

**Comment by minicatsCB** [comment]
![image](https://user-images.githubusercontent.com/19836547/50980120-42ff8e00-14f8-11e9-97d9-168474a62ac2.png)

Me uno por aquíí.

**Comment by UlisesGascon** [comment]
bravo @minicatsCB !!
