### ISSUE TITLE
[Oportunidad] ¡Salvemos Memezinga!

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#48]
![duat_i_x4amprob](https://user-images.githubusercontent.com/5110813/50217282-8f87fb80-0388-11e9-96df-c44f66217276.jpg)

**Si tienes tiempo y ganas... ¡es tu oportunidad!**

### Idea
- [x] Tirar todo y empezar de cero
- [ ] Ya que somos Guilders del Guild24... va siendo hora de tomar cartas en algunos proyectos ^^
- [ ] ¡Superemos al equipo del año pasado!
- [ ] Trabajo intenso en modo Agile con Code Reviews entre nostor@s y GitFlow
- [ ] Intentaremos simular un entorno de trabajo real con fechas de entrega y estimaciones. 
- [ ] Trabajaremos por parejas
- [ ] Haremos reuniones fuera de clase para coordinar
- [ ] Implementar nuevas funcionalidades usando "potencialmente" Firebase

### Básico
- [Somos @awesomemzg en Twitter](https://twitter.com/awesomemzg)
- [memezinga.com](http://memezinga.osweekends.com/)

**Comment by Optimus-73** [comment]
Let's rock !
