### ISSUE TITLE
Proyecto Miguel Angel Garcia

### ISSUE THREAD

**Issue by gargonmi** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#56]
### Segundo Proyecto

He pensado en realizar una plataforma para subir documentación relativa a la prevencion de riesgos laborales a las distintas plataformas que existen.

#### Contexto

Los centros comerciales , organismos y comunidades ,para asegurarse de que las empresas de servicios que contratan poseen toda la documentacion en regla en lo relativo a la prevencion de riesgos laborales, se dan de alta en diferentes plataformas en las que estas empresas deben subir toda la documentacion PRL . 
Estas plataformas validan la documentacion y dan el visto bueno a las empresas, y asi pueden realizar los trabajos.

#### Problematica actual

Sucede que al final las empresas de servicios deben subir la documentacion para **cada plataforma y cliente** por lo que al final deben repetir el proceso innumerables veces.

No hay muchas plataformas, pero cada platafoma no comparte los datos con sus diferentes clientes, por lo que el proceso se hace muy tedioso para las empresas 

#### La solucion

Una solucion consistiria en crear una aplicacion en la que hagamos login y subamos nuestra documentacion. Y esta aplicacion seria la que conectara con las diferentes plataformas y subiera la documentacion. Estando por lo tanto todo centralizado en una misma web y automatizando procesos.

**Comment by UlisesGascon** [comment]
Pues... mucho [puppeteer](https://github.com/GoogleChrome/puppeteer)

**Recursos**
- [Scraping épico para gente sin APIs - Ulises Gascón | T3chFest 2018](https://www.youtube.com/watch?v=-Gtv6BMvcgM)
- [Slides de la charla](https://cyber-nomads.slides.com/ulisesgascon/scraping-t3chfest-2018)
- [Ejemplo típico con booking](https://github.com/checkly/puppeteer-examples/blob/master/2.%20search/booking.js)
