### ISSUE TITLE
Proyecto de MinicatsCB

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#59]
### Algo tipo chat con un bot
- [Repo de ejemplo](https://github.com/firebase/friendlychat-web)
- [Code Lab](https://codelabs.developers.google.com/codelabs/firebase-web/#1)
- [Ejemplo de chat robotico](https://github.com/UlisesGascon/simple-hangouts-bot)
- [Firebase functions samples](https://github.com/firebase/functions-samples)

**Comment by minicatsCB** [comment]
Se me han ocurrido otras ideas:

### Una web (o app) para encontrar gente con tus mismos gustos deportivos
Por ejemplo, te gusta el baloncesto pero por las circunstancias que sean, no puedes jugar: eres nuevo en una ciudad, te faltan integrantes para el equipo, no sabes dónde hay canchas para jugar, etc.

Hay varias webs, pero no están actualizadas/mantenidas y el diseño, en mi opinión, no es que sea muy llamativo. Hay también apps móviles, pero les ocurre igual que a las webs, no están mantenidas o tienen poca actividad.

Incluso, podría ser algo tipo red social.

Ejemplos:
* [SportMeeting](https://sportmeeting.decathlon.com/login/auth) de Decathlon. Puedes buscar por deporte, lugar, nivel o fecha. La he probado y me gustó, lo único que hay poca actividad. La verdad, no entiendo por qué no le dan más difusión a la app.
- [Fubles](https://www.fubles.com/es/) Encontrar a gente para jugar al fútbol.
- [Timpik](http://www.timpik.com/) Encontrar a gente para practicar deporte, en general.

Había pensado que si esto es demasiado, podría hacerlo como proyecto final (si no se me ocurre otra cosa).

### Chat para hablar con gente con tu mismo hobby
He probado el tutorial del [Codelab](https://codelabs.developers.google.com/codelabs/firebase-web/#1) para hacer chats con firebase. El tutorial, por lo menos, ha sido sencillo. Idea: un chat al que puedes entrar y hablar con alguien que tenga tu mismo hobby. Para ello, haces un registro y, seguidamente, buscas filtrando por características de la persona y/o hobbie o eliges aleatoriamente. Nota: me da miedo que esto se pueda convertir en algún tipo de Tinder. :laughing: 

### Typing game
Un juego sobre mecanografía. Ya existe. Caen letras desde la parte de arriba de la pantalla y tienes que irlas pulsando. Cada vez van cayendo más rápido. Hay ranking. O pensar en alguna otra mecánica del juego. A lo mejor se puede meter Firebase para el ranking, o para el registro de las puntuaciones de los usuarios.
