### ISSUE TITLE
Proyecto Mauricio

### ISSUE THREAD

**Issue by codemcu** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#60]
### Segundo proyecto

**CRM** que permita gestionar en desde una misma app y base de datos la relación entre una escuela y los alumnos. 

Objetivos: 

- Contar con un perfil **Admin** y varios usuarios con permisos de **solo lectura** para administrar la aplicación
- **Alta y baja** de alumnos (_envío de mail_)
- **Subida y previsualización** de ficheros (_documentación_)
- **Generación** de datos a partir de esos ficheros
- Alta y baja de servicios contratados, contactos telefónico, gestión de cobros, etc etc (_opcional_)

**Comment by UlisesGascon** [comment]
**Email**
- https://github.com/firebase/functions-samples/tree/Node-8/quickstarts/email-users
- https://github.com/firebase/functions-samples/tree/Node-8/email-confirmation

**Previsualización**
- https://github.com/firebase/functions-samples/tree/Node-8/generate-thumbnail
- https://github.com/firebase/functions-samples/tree/Node-8/image-sharp
- https://github.com/firebase/functions-samples/tree/Node-8/moderate-images

**Comment by UlisesGascon** [comment]
### Opción B: 
**Caracteristicas**
- Varias cuentas de twitter como https://twitter.com/os_weekends o https://twitter.com/oswguilds
- herramientas que usamos hoy: buffer, tweetdeck, twitter clientes nativos

**Objetivos**
- Logearse en https://comparte.osweekends.com con alguna red social de turno para evitar troleos (sin permisos, solo info...)
- Que la gente pudiera proponer un tweet y enviarlo para confirmación.
- Avise por email? a la gente de la organización para que accionen.
- El mensaje se puede editar, enviar o rechazar.
- El "backend" se encarga de publicar o eliminar ese tweet usando la API de twitter y las credenciales...

**Objetivos extras**
- Poder proponer un tweet con una fecha y hora...
- Poder proponer repeticiones de ese mismo tweet...

**Vistas**
- `/` -> landing/info... 
- `/login` -> donde pinchas para logearte...
- `/create` -> generas una propuesta de nuevo tweet 
- `/admin` -> que apruebas/editas/modificas/Cancelas... los tweets

**Herramientas**
- Firebase (login)
- Firebase (realtime database)
- Firebase (cloud functions): email, api de twitter (triggers)
- router con HTML5...

**Recursos**
- [Auth trigger quickstart: Welcome Email](https://github.com/firebase/functions-samples/tree/Node-8/quickstarts/email-users)
- [Email confirmation](https://github.com/firebase/functions-samples/tree/Node-8/email-confirmation)
