### ISSUE TITLE
Invertir los valores binarios de una imagen. aka Inventator!

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#65]
### Pasos...
- Pillar una imagen
- La pintamos en el canvas
- Recuperamos los datos 
- Transformación en binario
- Pintado de vuelta

**Comment by Optimus-73** [comment]
### Repositorio imageInverter: https://github.com/Optimus-73/imageInverter
![prueba2](https://user-images.githubusercontent.com/20280508/51635136-61cd3e00-1f56-11e9-8434-33bc55005429.jpg)
![canvas](https://user-images.githubusercontent.com/20280508/51635148-68f44c00-1f56-11e9-9ced-9530a2c7b5b3.png)
