### ISSUE TITLE
Sería coherente utilizar un "compositor" en este caso ?

### ISSUE THREAD

**Issue by Optimus-73** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#67]
Estaba trabajando en el proyecto de la lista de contactos cuando me he encontrado con el siguiente dilema:

La mayoría de funciones que he creado acaban modificando el DOM con una función a la que he llamado ```drawData()```. Entonces recordé el compositor que vimos en la clase de programación funcional.
Aunque en realidad en este caso una función no depende de la otra sino que las funciones deben ser ejecutadas consecutivamente. Con esto conseguiría que la función ```drawData()``` no tuviese que ser siempre llamada desde el resto de funciones.

```javascript
let compositor = (f, g) => { f(); g(); }
```

```html
<button onclick="compositor(saveData(), drawData())">Guardar</button>
```

Entonces, mi pregunta es: esto realmente tiene algún sentido plantearlo de esta manera o sería mejor que llamase a ```drawData()``` al terminar cada función ?

**Comment by UlisesGascon** [comment]
Es un enfoque bastante interesante! En principio lo más interesante del compositor es generar una nueva función que puedas reutilizar.  :-)

Pero si lo que realmente te estás planteando es hacer son secuencias de pasos síncronos, solo necesitarías construirte una cola. El reto esta en la asincronía, pero tienes cosas molonas como [essetane/queue](https://github.com/jessetane/queue)
