### ISSUE TITLE
Primer proyecto Miguel Angel Garcia 

### ISSUE THREAD

**Issue by gargonmi** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#8]
He pensado hacer una especie de piano virtual.. En principio no tiene mucha utilidad..pero la idea es que vaya ganando funcionalidades como por ejemplo poder introducir partiruras e incluso en un futuro manejarlo via midi o teclado . 
Con respecto a las llamadas Ajax, esto mirando Apis para ver como hacerlo..

**Comment by minicatsCB** [comment]
A mí me encanta la idea! Es algo que siempre me ha rondado por la cabeza hacer. :+1:

**Comment by calope03** [comment]
https://www.acrcloud.com/blog/music-apis-the-list-of-2016  echale un ojo a estas ultimas por si te da alguna idea, alguna de las ultimas te podria servir. 

Yo viendo estas cosas lo mas "sencillo" que se me ocurriria es utilizar alguna de las de partituras para mostrarlas a la vez que el piano y asi tener una partirua delante.

**Comment by gargonmi** [comment]
Muchas gracias , le echare un ojo a ver...
Seguro que alguna me sirve...

**Comment by UlisesGascon** [comment]
- https://musiclab.chromeexperiments.com/Chords/
- https://musiclab.chromeexperiments.com/Voice-Spinner/
- https://experiments.withgoogle.com/ai/ai-duet/view/
- https://codepen.io/baileyparker/pen/pgPxYZ
- https://codepen.io/dan10gc/pen/EvgKyo
- https://codepen.io/joshfry/pen/utHlL
- https://codepen.io/helvetica/pen/GNzgYz
- https://mrcoles.com/piano/
- http://www.keithwhor.com/music/
- https://experiments.withgoogle.com/


### MIDI Files y conversión
- https://tonejs.github.io/examples/#simpleSynth
- https://en.wikipedia.org/wiki/File:MIDI_sample.mid?qsrc=3044
- https://tonejs.github.io/MidiConvert/
- https://github.com/googlecreativelab/aiexperiments-ai-duet
