### ISSUE TITLE
Primer proyecto Maribel Díaz

### ISSUE THREAD

**Issue by minicatsCB** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed2#9]
Mi idea no es original, pero consistiría en una aplicación en la que tú puedes meter los ingredientes que tienes en el frigorífico (o en tu casa en general) y recibes posibles recetas que contengan esos ingredientes. Algunas características serían:
- Las recetas que contengan alguno de tus ingredientes pero le falte alguno, te dice cuáles son.
- También puedes filtrar por tiempo de preparación, precio aproximado, dificultad, calorías aportadas, etc.
- Un plus, que no sé hasta que punto es factible, es que te compare sitios y precios donde puedes comprar esos ingredientes (Mercadona, Alcampo, Carrefour, etc).

Utilizaría la API [spoonacular](https://spoonacular.com/food-api).

**Comment by UlisesGascon** [comment]
- Localstorage (lista)

- Sugerencias
- https://market.mashape.com/spoonacular/recipe-food-nutrition
- Token?

- https://github.com/ndillon1/RecipeApp
- https://github.com/topics/spoonacular
